# Name des Workflows
name: Häufiger Cron-Job

# Trigger: Wird durch ein geplantes Ereignis (cron) ausgelöst
on:
  schedule:
    # Cron-Ausdruck: Läuft jeden Tag um 05:30 UTC
    # Format: 'Minute Stunde Tag Monat Wochentag'
    - cron: '*/5 * * * *'

# Jobs, die ausgeführt werden sollen
jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      # Erster Schritt: Auschecken des Repositorys
      - name: Repository auschecken
        uses: actions/checkout@v4

      # Zweiter Schritt: Ausführen eines einfachen Befehls
      - name: Aktuelle Zeit ausgeben
        run: date
        # Dieser Befehl gibt das aktuelle Datum und die Uhrzeit aus
